name: Run Pest Tests

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - 'CHANGELOG.md'
      - 'CONTRIBUTING.md'
      - 'doc/**'

jobs:
  phpunit:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: [ 8.2, 8.3, 8.4 ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: xdebug

      - name: Install dependencies
        run: composer install --no-progress --no-suggest --prefer-dist

      - name: Configure Xdebug
        run: echo "xdebug.mode=coverage" >> $GITHUB_ENV

      - name: Run Pest
        run: vendor/bin/pest